const GUEST_ACTION_TYPES = 'study-files/guest';

export const GET_TEACHER_INFO = `${GUEST_ACTION_TYPES}/GET_TEACHER_INFO`;
export const GET_TEACHER_COURSES = `${GUEST_ACTION_TYPES}/GET_TEACHER_COURSES`;
