const TEACHER_ACTION_TYPES = 'study-files/teacher';

export const GET_COURSE_DETAILS = `${TEACHER_ACTION_TYPES}/GET_COURSE_DETAILS`;
export const GET_CATEGORIES_DETAILS = `${TEACHER_ACTION_TYPES}/GET_CATEGORIES_DETAILS`;
export const GET_SECTIONS_RESULTS = `${TEACHER_ACTION_TYPES}/GET_SECTIONS_RESULTS`;
